version: 1

run:
  timeout: 5m

linters:

  enable:
    - gofmt
    - goimports
    - govet
    - unused
    - revive

linters-settings:
  revive:
    rules:
      - name: package-comments
        disabled: true
      - name: exported
        disabled: true

issues:
  exclude-use-default: false
